# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 762afb1a9927ffa499bfbb7b158ee46289023d9298981f2acfcb2323201e35121ef6270c83232e7023f65340aaa01327a164f7e03f8fcec409af748a881e6f5b

test:
  secret_key_base: 936b9b8a5e4815e6e6acf02a4f818b6ac343f57dcd63569560aaf503bb3851514ce2bb6c5a0437dea329b3a5081983321f73fb9f20cdcd1e913d36efc3d8527e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
